Dynamically create blocks catalog
PrefectHQ/prefect-collection-template pull request #113
Opened 2022-12-22 20:28 UTC by ahuang11

2022-12-22 20:32 UTC, ahuang11 commented on {{cookiecutter.collection_name}}/docs/gen_ref_pages.py
> +    )
```suggestion
    generated_file.write(
        "Below is a list of Blocks available for registration in "
        "`{{ cookiecutter.collection_name }}`.\n\n"
    )
```

2022-12-23 20:09 UTC, desertaxle requested changes

2022-12-23 20:09 UTC, desertaxle commented on {{cookiecutter.collection_name}}/README.md
> +A list of available blocks in `prefect-gcp` and their setup instructions can be found [here](https://github.com/{{ cookiecutter.github_organization }}/{{ cookiecutter.collection_name }}/#blocks-catal
```suggestion
A list of available blocks in `{{ cookiecutter.collection_name }}` and their setup instructions can be found [here](https://github.com/{{ cookiecutter.github_organization }}/{{ cookiecutter.collection_name }}/#blocks-catalog/).
```

2022-12-23 20:09 UTC, desertaxle commented on {{cookiecutter.collection_name}}/docs/gen_ref_pages.py
> +    return module_blocks
Should we use the registry to find blocks like you did in https://github.com/PrefectHQ/prefect-collection-template/pull/114?

2022-12-24 01:27 UTC, ahuang11 commented on {{cookiecutter.collection_name}}/docs/gen_ref_pages.py
> +                </details>
```suggestion
```

2022-12-24 01:29 UTC, ahuang11 commented on {{cookiecutter.collection_name}}/docs/gen_ref_pages.py
> +            `{{ cookiecutter.COLLECTION_SLUG }}`.
```suggestion
            `{{ cookiecutter.collection_name }}`.
```

2022-12-28 17:36 UTC, desertaxle requested changes

2022-12-28 17:36 UTC, desertaxle commented on {{cookiecutter.collection_name}}/docs/gen_ref_pages.py
> +from prefect.utilities.dispatch import get_registry_for_type
```suggestion
from prefect.utilities.dispatch import get_registry_for_type
from prefect.utilities.importtools import to_qualified_name
```

2022-12-28 17:37 UTC, desertaxle approved these changes

2022-12-28 17:37 UTC, merged