Add badges
PrefectHQ/prefect-collection-template pull request #67
Opened 2022-08-11 21:12 UTC by ahuang11

https://github.com/PrefectHQ/prefect-collection-template/issues/13

2022-08-11 21:17 UTC, ahuang11 commented
Tested generation successfully:
```
[![PyPI version](https://badge.fury.io/py/prefect-aws.svg)](https://pypi.python.org/pypi/prefect-aws/)
[![PyPI pyversions](https://img.shields.io/pypi/pyversions/prefect-aws.svg)](https://pypi.python.org/pypi/prefect-aws/)
[![Downloads](https://pepy.tech/badge/prefect-aws)](https://pepy.tech/project/prefect-aws)
[![Stars](https://img.shields.io/github/stars/prefecthq/prefect-aws)](https://github.com/prefecthq/prefect-aws/)
[![PyPI license](https://img.shields.io/pypi/l/prefect-aws.svg)](https://pypi.python.org/pypi/prefect-aws/)
```

![image](https://user-images.githubusercontent.com/15331990/184243809-be4d047f-24c5-4647-932f-c5c635480b0c.png)

2022-08-12 03:00 UTC, ahuang11 commented
![image](https://user-images.githubusercontent.com/15331990/184276979-03547423-b6f0-41ef-a32c-64b65982a7e0.png)

2022-08-12 04:37 UTC, ahuang11 commented
Should we add discourse and slack?
https://img.shields.io/discourse/users?server=https%3A%2F%2Fdiscourse.prefect.io
```
    <a href="https://discourse.prefect.io/"" alt="Discourse">
        <img src="https://img.shields.io/discourse/users?server=https%3A%2F%2Fdiscourse.prefect.io" /></a>
```

2022-08-12 15:36 UTC, desertaxle commented
Yeah, I think adding Discourse and Slack would be great

2022-08-12 20:31 UTC, ahuang11 commented
![image](https://user-images.githubusercontent.com/15331990/184439768-6c620f1e-dd1b-4b1c-abe3-920473a30e07.png)

2022-08-15 15:07 UTC, desertaxle requested changes

2022-08-15 15:07 UTC, desertaxle commented on {{cookiecutter.collection_name}}/README.md
> +    <img src="https://img.shields.io/github/stars/{{ cookiecutter.github_organization }}/{{ cookiecutter.collection_name }}" /></a>
I think this needs to be replaced with a PyPI version badge

2022-08-16 19:27 UTC, ahuang11 commented
![image](https://user-images.githubusercontent.com/15331990/184965311-ac4e3392-1d4f-4db1-9232-0bbb454cf2fe.png)

2022-08-16 19:30 UTC, desertaxle approved these changes

2022-08-16 19:33 UTC, merged