Add info about registering block
PrefectHQ/prefect-collection-template pull request #68
Opened 2022-08-12 21:55 UTC by ahuang11

So users are not confused about why blocks not showing on the Cloud

2022-08-15 14:52 UTC, desertaxle requested changes
Can you include a sample block in the template in this PR also?

2022-08-15 22:46 UTC, ahuang11 commented
Can you elaborate what kind of sample block?

2022-08-16 22:07 UTC, ahuang11 commented
flows.py
```
"""This is an example flows module"""
from prefect import flow

from prefect_collection.tasks import (
    goodbye_prefect_collection,
    hello_prefect_collection,
)
from prefect_collection.blocks import CollectionBlock


@flow
def hello_and_goodbye():
    """
    Sample flow that says hello and goodbye!
    """
    CollectionBlock().seed_value_for_example()
    block = CollectionBlock.load("sample-block")

    print(hello_prefect_collection())
    print(f"The block's value: {block.value}")
    print(goodbye_prefect_collection())
    return "Done"


if __name__ == "__main__":
    hello_and_goodbye()

```

```
"""This is an example blocks module"""

from prefect.blocks.core import Block
from pydantic import Field


class CollectionBlock(Block):
    """
    A sample block that holds a value.

    Args:
        value (str): The value to store.
    
    Example:
        Load a stored value:
        ```python
        from prefect_collection import CollectionBlock
        block = CollectionBlock.load("BLOCK_NAME")
        ```
    """

    value: str = Field("The default value", description="The value to store")

    @classmethod
    def seed_value_for_example(cls):
        block = cls(value="A sample value")
        block.save("sample-block", overwrite=True)

```

2022-08-19 13:34 UTC, desertaxle approved these changes

2022-08-22 23:31 UTC, merged